import { IProduct } from '@/types/product'

export const PRODUCTS: IProduct[] = [
  {
    id: 'cursed-tshirt',
    type: 'T-Shirt',
    collection: 'Cursed',
    price: 30,
    color: '#6700F7',
    textColor: '#fff',
    haloColor: 'rgba(103, 0, 247, 0.5)',
    variants: [{ name: 'Black', color: '#242424', availability: ['s', 'm', 'l', 'xl', 'xxl'] }],
    imgs: ['front'],
  },
  {
    id: 'hazard-hoodie',
    type: 'Hoodie',
    collection: 'Hazard',
    price: 60,
    color: '#FFDE02',
    textColor: '#242424',
    haloColor: 'rgba(255, 222, 2, 0.5)',
    variants: [{ name: 'Black', color: '#242424', availability: ['m', 'l', 'xl'] }],
    imgs: ['front', 'back'],
  },
  {
    id: 'valentine-jacket',
    type: 'Jacket',
    collection: 'Valentine',
    price: 80,
    color: '#EAB8D9',
    textColor: '#242424',
    haloColor: 'rgba(234, 184, 217, 0.5)',
    variants: [{ name: 'Pink', color: '#EAB8D9', availability: ['m'] }],
    imgs: ['back'],
  },
  {
    id: 'yiik-tshirt',
    type: 'T-Shirt',
    collection: 'Yiik',
    price: 30,
    color: '#ccfc00',
    textColor: '#242424',
    haloColor: 'rgba(204, 252, 0, 0.5)',
    variants: [{ name: 'Lime', color: '#ccfc00', availability: ['s'] }],
    imgs: ['front'],
  },
  {
    id: 'minimal-hoodie',
    type: 'Hoodie',
    collection: 'Minimal',
    price: 60,
    color: '#5CEFF6',
    textColor: '#242424',
    haloColor: 'rgba(255, 255, 255, 0.75)',
    variants: [
      { name: 'White', color: '#fff', availability: [] },
      { name: 'Black', color: '#242424', availability: ['m'] },
    ],
    imgs: ['front', 'back'],
  },
  {
    id: 'cursed-jacket',
    type: 'Jacket',
    collection: 'Cursed',
    price: 80,
    color: '#6700F7',
    textColor: '#fff',
    haloColor: 'rgba(103, 0, 247, 0.5)',
    variants: [{ name: 'Black', color: '#242424', availability: [] }],
    imgs: ['back'],
  },
  {
    id: 'dogs-tshirt',
    type: 'T-Shirt',
    collection: 'Dogs',
    price: 30,
    color: '#242424',
    textColor: '#fff',
    haloColor: 'rgba(255, 255, 255, 0.5)',
    variants: [{ name: 'Black', color: '#242424', availability: [] }],
    imgs: ['front'],
  },
  {
    id: 'og-hoodie',
    type: 'Hoodie',
    collection: 'OG',
    price: 60,
    color: '#eec16b',
    textColor: '#242424',
    haloColor: 'rgba(238, 193, 107, 0.5)',
    variants: [
      { name: 'Black', color: '#242424', availability: [] },
      { name: 'White', color: '#fff', availability: [] },
    ],
    imgs: ['back', 'front'],
  },
  {
    id: 'og-cap',
    type: 'Cap',
    collection: 'OG',
    price: 30,
    color: '#eec16b',
    textColor: '#242424',
    haloColor: 'rgba(238, 193, 107, 0.5)',
    variants: [{ name: 'Black', color: '#242424', availability: ['l'] }],
    imgs: ['side'],
  },
]
